### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/PolyesterForwardDiff.jl#3]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by oscardssmith** [comment]
@JuliaRegistrator register()
